### ISSUE TITLE
只能提取其中一页的问题

### ISSUE THREAD

**Issue by michaelmifb** [chenaive/fuck-volmoe#2]
关于那些一个文件里面有很多话的epub，软件只能提取每一话的第一页。
其它的都不能提取。

例子：
[Kox][一拳超人(原作版)]話001-009.kepub.epub

我只能提取到9张图案，001-009的第一张图案。

**Comment by chenaive** [comment]
您好，能否附上出问题的文件？我再试试看

**Comment by michaelmifb** [comment]
您好，附上未能解压的文件。
https://drive.google.com/file/d/1xMegD7mXzF2CRcxto6b29yD971vvkL7B/view?usp=sharing

**Comment by chenaive** [comment]
已经更新了新版本，请试用
